#!/usr/bin/env bash
set -euo pipefail

# ----------------------------------------
# Vulkan bootstrapper for llama.rn
# - Builds host-side vulkan-shaders-gen
# - Clones Vulkan-Headers
# - Generates embedded SPIR-V shader blobs
# ----------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GGML_VK_DIR="$ROOT_DIR/cpp/ggml-vulkan"
VK_SHADERS="$GGML_VK_DIR/vulkan-shaders"
HOST_BUILD="$VK_SHADERS/build-host"
OUT_DIR="$GGML_VK_DIR/vk_autogen"
SPV_DIR="$OUT_DIR/vulkan-shaders.spv"

VKH_DIR="$ROOT_DIR/third_party/Vulkan-Headers"
VULKAN_HEADERS_SUBMODULE=third_party/Vulkan-Headers
VKH_TAG="vulkan-sdk-1.3.283.0"   # tag example
VKH_BRANCH="vulkan-sdk-1.3.283" # set to "main" or similar if needed

mkdir -p "$OUT_DIR" "$SPV_DIR" "$ROOT_DIR/third_party"

echo "==> Bootstrapping Vulkan-Headers…"

# Pin to a specific tag (preferred for SDK versions)
if [ -n "$VKH_TAG" ]; then
  git submodule update --init --recursive "$VULKAN_HEADERS_SUBMODULE"
  git -C "$VKH_DIR" fetch --tags --quiet
  git -C "$VKH_DIR" checkout --quiet "tags/$VKH_TAG"

# Or switch to a specific branch
elif [ -n "$VKH_BRANCH" ]; then
  git submodule update --init --recursive "$VULKAN_HEADERS_SUBMODULE"
  git -C "$VKH_DIR" fetch origin "$VKH_BRANCH" --quiet
  git -C "$VKH_DIR" checkout --quiet "$VKH_BRANCH"
  git submodule set-branch --branch "$VKH_BRANCH" "$VULKAN_HEADERS_SUBMODULE" >/dev/null 2>&1 || true
fi

VULKAN_HEADERS_DIR="$VKH_DIR/include"
[[ -d "$VULKAN_HEADERS_DIR/vulkan" ]] || { echo "❌ Vulkan headers missing in $VKH_DIR"; exit 1; }
echo "✓ Vulkan-Headers ready at: $VULKAN_HEADERS_DIR"

# ---------- Check GLSLC ----------
GLSLC_BIN="${GLSLC_BIN:-}"
if [[ -z "$GLSLC_BIN" ]]; then
  if [[ -n "${VULKAN_SDK:-}" && -x "$VULKAN_SDK/bin/glslc" ]]; then
    GLSLC_BIN="$VULKAN_SDK/bin/glslc"
  elif command -v glslc >/dev/null 2>&1; then
    GLSLC_BIN="$(command -v glslc)"
  fi
fi
[[ -x "$GLSLC_BIN" ]] || { echo "❌ glslc not found (install Vulkan SDK or set GLSLC_BIN)"; exit 1; }
echo "✓ glslc found at: $GLSLC_BIN"

# ---------- Build host helper ----------
echo "==> Building vulkan-shaders-gen (host)..."
rm -rf "$HOST_BUILD"
cmake -S "$VK_SHADERS" -B "$HOST_BUILD" -G Ninja -DGGML_VULKAN_INTEGER_DOT_GLSLC_SUPPORT=1 -DCMAKE_BUILD_TYPE=Release
cmake --build "$HOST_BUILD" --config Release

# find executable
GEN_EXE=""
for p in \
  "$HOST_BUILD/vulkan-shaders-gen" \
  "$HOST_BUILD/vulkan-shaders-gen.exe" \
  "$HOST_BUILD/Release/vulkan-shaders-gen.exe" \
  "$HOST_BUILD/Debug/vulkan-shaders-gen.exe"
do
  [[ -x "$p" ]] && GEN_EXE="$p" && break
done
[[ -n "$GEN_EXE" ]] || { echo "❌ vulkan-shaders-gen not found after build"; exit 1; }
echo "✓ generator: $GEN_EXE"

# ---------- Generate embedded shaders ----------
echo "==> Generating embedded shaders..."
"$GEN_EXE" \
  --glslc "$GLSLC_BIN" \
  --glslc-arg="-std=450" \
  --glslc-arg="-fshader-stage=compute" \
  --glslc-arg="--target-env=vulkan1.3" \
  --glslc-arg="--target-spv=spv1.6" \
  --input-dir "$VK_SHADERS" \
  --output-dir "$SPV_DIR" \
  --target-hpp "$OUT_DIR/ggml-vulkan-shaders.hpp" \
  --target-cpp "$OUT_DIR/ggml-vulkan-shaders.cpp" \
  --no-clean

# ---------- Write helper CMake include ----------
cat > "$GGML_VK_DIR/VulkanHeaders.cmake" <<EOF
# Auto-generated by bootstrap-vulkan.sh
set(VULKAN_HEADERS_DIR "\${CMAKE_SOURCE_DIR}/../../../third_party/Vulkan-Headers/include" CACHE PATH "Khronos Vulkan-Headers include dir")
EOF

echo ""
echo "✅ Vulkan bootstrap complete!"
echo "  Embedded C++ : $OUT_DIR/ggml-vulkan-shaders.cpp/.hpp"
echo "  SPIR-V Blobs : $SPV_DIR"
echo "  Headers      : $VULKAN_HEADERS_DIR"
echo "  Helper CMake : $GGML_VK_DIR/VulkanHeaders.cmake"
